# Generated by Django 5.2.13 on 2026-04-26 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='games/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('DR', 'DRIVING'), ('RC', 'RACING'), ('PB', 'PUBG'), ('CH', 'CHESS')], max_length=2)),
            ],
        ),
    ]
